import type { Metadata } from "next";
import Link from "next/link";

import { getProvider } from "@/lib/api";
import { SectionHeading } from "@/components/ui/primitives";
import { ButtonLink } from "@/components/ui/button";
import { formatNumber, relativeTime } from "@/lib/formatters";
import { site } from "@/config/site";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "About",
  description:
    "OmniStore is a universal discovery and distribution interface for open-source applications, powered by OmniSource.",
  alternates: { canonical: "/about" },
};

export default async function AboutPage() {
  const provider = getProvider();
  const [stats, meta] = await Promise.all([provider.getStats(), provider.getFeedMeta()]);

  return (
    <div className="mx-auto max-w-3xl space-y-10">
      <header className="space-y-3">
        <h1 className="text-3xl font-semibold tracking-tight">About OmniStore</h1>
        <p className="text-lg text-muted">
          A universal discovery and distribution interface for open-source applications across iOS,
          iPadOS, Android, Windows, macOS and Linux.
        </p>
      </header>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">What OmniStore is</h2>
        <p className="text-muted">
          OmniStore exists to make open-source software easy to find, understand and download. It
          indexes upstream projects, normalises their release artefacts into platforms, architectures
          and package types, computes explainable scores from public signals, and presents everything
          in one interface — without hiding or replacing the upstream project.
        </p>
        <p className="text-muted">
          OmniStore is <strong>not</strong> an app store of record. It does not host binaries, does
          not mirror installers, and does not take ownership of third-party software. Downloads go
          straight to the upstream release.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">The catalog right now</h2>
        <dl className="grid gap-4 sm:grid-cols-3">
          <Stat label="Applications" value={formatNumber(stats.apps)} />
          <Stat label="Verified packages" value={formatNumber(stats.validatedAssets)} />
          <Stat label="Developers" value={formatNumber(stats.developers)} />
        </dl>
        <p className="text-2xs text-fg-subtle">
          Catalog snapshot {relativeTime(meta.generated_at)} · generated by {meta.generator} · upstream{" "}
          {meta.upstream}
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">How data is sourced</h2>
        <ul className="list-disc space-y-2 pl-5 text-muted">
          <li>
            A curated registry of upstream repositories is ingested by the OmniSource pipeline
            (<code className="rounded bg-surface-2 px-1 text-2xs">npm run ingest</code>).
          </li>
          <li>
            Repository metadata, releases and artefacts are fetched from the upstream API — versions,
            dates, sizes, licences and download URLs are all upstream values.
          </li>
          <li>
            Artefacts are normalised to platform / architecture / package type. Anything that cannot
            be classified confidently is dropped rather than guessed.
          </li>
          <li>
            Scores are computed from those upstream signals and published with their full factor
            breakdown.
          </li>
          <li>No screenshots, ratings or review counts are invented. Missing data reads “Not available”.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Relationship to OmniSource</h2>
        <p className="text-muted">
          OmniSource provides the intelligence and data layer: ingestion, normalisation, validation,
          scoring and the versioned API. OmniStore Web is the first complete client built on that
          contract. Future OmniStore clients for iOS, Android, Windows, macOS and Linux will reuse the
          same API and the same normalised data model.
        </p>
        <p className="text-muted">
          Read <Link href="/docs" className="text-accent hover:underline">the documentation</Link> for
          the full client contract, or browse the{" "}
          <a
            href={site.omnisourceRepoUrl}
            target="_blank"
            rel="noopener noreferrer external"
            className="text-accent hover:underline"
          >
            OmniSource repository
          </a>
          .
        </p>
      </section>

      <SectionHeading title="Start exploring" />
      <div className="flex flex-wrap gap-3">
        <ButtonLink href="/apps">Explore Apps</ButtonLink>
        <ButtonLink href="/platforms" variant="outline">
          Browse Platforms
        </ButtonLink>
        <ButtonLink href="/discover/cross-platform" variant="outline">
          Cross-Platform Apps
        </ButtonLink>
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="card p-4">
      <dt className="text-2xs uppercase tracking-wide text-fg-subtle">{label}</dt>
      <dd className="mt-1 text-2xl font-semibold tabular-nums">{value}</dd>
    </div>
  );
}
