"use client";

import { useEffect, useState } from "react";
import { WifiOff } from "lucide-react";
import { useTranslations } from "next-intl";

/**
 * Registers the service worker (generated by @ducanh2912/next-pwa) and
 * renders an offline banner when the network drops.
 */
export function Pwa() {
  useEffect(() => {
    if (process.env.NODE_ENV !== "production") return;
    if (!("serviceWorker" in navigator)) return;
    const register = () => {
      navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch(() => {
        /* SW registration is best-effort */
      });
    };
    register();
  }, []);

  return <OfflineBanner />;
}

function OfflineBanner() {
  const t = useTranslations("common");
  const [offline, setOffline] = useState(false);

  useEffect(() => {
    const update = () => setOffline(!navigator.onLine);
    update();
    window.addEventListener("online", update);
    window.addEventListener("offline", update);
    return () => {
      window.removeEventListener("online", update);
      window.removeEventListener("offline", update);
    };
  }, []);

  if (!offline) return null;
  return (
    <div
      role="status"
      className="sticky top-16 z-30 flex items-center justify-center gap-2 bg-warning/15 px-4 py-1.5 text-xs font-medium text-warning"
    >
      <WifiOff className="h-3.5 w-3.5" aria-hidden />
      {t("offline")}
    </div>
  );
}
