#!/usr/bin/env node
/**
 * build-catalog.mjs — regenerate website/js/catalog.js from the bundled feed.
 *
 * The OmniStore-Pro website is static and must stay honest: every number and
 * every app shown on it comes from data/omnisource-feed.json, never hand-typed.
 *
 * Usage:
 *   node website/scripts/build-catalog.mjs          # from the repo root
 *   node scripts/build-catalog.mjs --feed <path>    # custom feed location
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

function argValue(name, fallback) {
  const i = process.argv.indexOf(name);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const feedPath = argValue(
  "--feed",
  join(here, "..", "..", "data", "omnisource-feed.json"),
);

const feed = JSON.parse(readFileSync(feedPath, "utf8"));

/** Icon URLs that are not real images (empty, protocol-relative, non-https). */
function safeIcon(icon) {
  return typeof icon === "string" && /^https:\/\/avatars\.githubusercontent\.com\//.test(icon)
    ? icon
    : null;
}

const apps = feed.apps ?? [];

/** Deduplicate by icon so one org does not own the whole marquee. */
function dedupByIcon(list) {
  const seen = new Set();
  const out = [];
  for (const app of list) {
    const icon = safeIcon(app.icon);
    const key = icon ?? app.name;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ app, icon });
  }
  return out;
}

const score = (app, key) => (app.scores ?? {})[key] ?? 0;

// Marquee: the most popular apps, icon-deduplicated, with real upstream links.
const marquee = dedupByIcon(
  [...apps].sort((a, b) => score(b, "popularity") - score(a, "popularity")),
)
  .slice(0, 44)
  .map(({ app, icon }) => ({
    name: app.name,
    icon,
    license: app.license && app.license !== "None" ? app.license : null,
    url: app.repository ?? app.homepage ?? null,
  }));

// Storefront window: the real featured collection, icon-deduplicated.
const featured = dedupByIcon(
  apps.filter((a) => a._featured).sort((a, b) => score(b, "trust") - score(a, "trust")),
)
  .slice(0, 8)
  .map(({ app, icon }) => ({
    name: app.name,
    icon,
    trust: score(app, "trust"),
    category: (app.categories ?? [])[0] ?? null,
    url: app.repository ?? null,
  }));

// Categories with real counts.
const categories = (feed.categories ?? []).map((c) => ({
  slug: c.slug,
  name: c.name,
  count: c.app_count ?? 0,
  description: c.description ?? null,
}));

// Platforms with real counts.
const platforms = (feed.platforms ?? []).map((p) => ({
  name: p.display_name ?? p.name,
  count: p.app_count ?? 0,
}));

// Curated collections (public ones only).
const collections = (feed.collections ?? [])
  .filter((c) => c.is_public)
  .slice(0, 8)
  .map((c) => ({
    name: c.name,
    description: c.description ?? null,
    count: c.item_count ?? 0,
  }));

const stats = {
  apps: feed.stats?.applications ?? apps.length,
  repositories: feed.stats?.repositories ?? apps.length,
  releases: feed.stats?.releases ?? 0,
  assets: feed.stats?.assets ?? 0,
  developers: feed.stats?.developers ?? (feed.developers ?? []).length,
  categories: categories.length,
  platforms: platforms.length,
};

const payload = {
  generatedAt: feed.generated_at ?? new Date().toISOString(),
  schemaVersion: feed.schema_version ?? 1,
  stats,
  marquee,
  featured,
  categories,
  platforms,
  collections,
};

const outPath = join(here, "..", "js", "catalog.js");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  [
    "/**",
    " * catalog.js — REAL catalog data for the OmniStore-Pro website.",
    " *",
    " * Generated by website/scripts/build-catalog.mjs from data/omnisource-feed.json.",
    ` * Feed generated: ${payload.generatedAt} · ${stats.apps} apps · ${stats.releases} releases · ${stats.assets} assets`,
    " * Do not edit by hand — re-run the script after `npm run ingest`.",
    " */",
    `window.OMNI_CATALOG = ${JSON.stringify(payload, null, 2)};`,
    "",
  ].join("\n"),
);

console.log(
  `✓ wrote ${outPath} — ${stats.apps} apps, ${marquee.length} marquee entries, ${featured.length} featured, ${categories.length} categories, ${platforms.length} platforms, ${collections.length} collections`,
);
