/**
 * catalog.js — REAL catalog data for the OmniStore-Pro website.
 *
 * Generated by website/scripts/build-catalog.mjs from data/omnisource-feed.json.
 * Feed generated: 2026-09-13T22:23:27.201Z · 444 apps · 1907 releases · 13444 assets
 * Do not edit by hand — re-run the script after `npm run ingest`.
 */
window.OMNI_CATALOG = {
  "generatedAt": "2026-09-13T22:23:27.201Z",
  "schemaVersion": 1,
  "stats": {
    "apps": 444,
    "repositories": 444,
    "releases": 1907,
    "assets": 13444,
    "developers": 416,
    "categories": 11,
    "platforms": 5
  },
  "marquee": [
    {
      "name": ".NET MAUI",
      "icon": "https://avatars.githubusercontent.com/u/9141961?v=4",
      "license": "MIT",
      "url": "https://github.com/dotnet/maui"
    },
    {
      "name": "Actual Budget",
      "icon": "https://avatars.githubusercontent.com/u/37879538?v=4",
      "license": "MIT",
      "url": "https://github.com/actualbudget/actual"
    },
    {
      "name": "AdGuard Home",
      "icon": "https://avatars.githubusercontent.com/u/8361145?v=4",
      "license": "GPL-3.0",
      "url": "https://github.com/AdguardTeam/AdGuardHome"
    },
    {
      "name": "AFFiNE",
      "icon": "https://avatars.githubusercontent.com/u/78728988?v=4",
      "license": "Other",
      "url": "https://github.com/toeverything/AFFiNE"
    },
    {
      "name": "age",
      "icon": "https://avatars.githubusercontent.com/u/1225294?v=4",
      "license": "BSD-3-Clause",
      "url": "https://github.com/FiloSottile/age"
    },
    {
      "name": "Alacritty",
      "icon": "https://avatars.githubusercontent.com/u/29714349?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/alacritty/alacritty"
    },
    {
      "name": "Angry IP Scanner",
      "icon": "https://avatars.githubusercontent.com/u/29024081?v=4",
      "license": "GPL-2.0",
      "url": "https://github.com/angryip/ipscan"
    },
    {
      "name": "Anki",
      "icon": "https://avatars.githubusercontent.com/u/42564322?v=4",
      "license": "Other",
      "url": "https://github.com/ankitects/anki"
    },
    {
      "name": "Ant Design",
      "icon": "https://avatars.githubusercontent.com/u/12101536?v=4",
      "license": "MIT",
      "url": "https://github.com/ant-design/ant-design"
    },
    {
      "name": "AntennaPod",
      "icon": "https://avatars.githubusercontent.com/u/10713470?v=4",
      "license": "GPL-3.0",
      "url": "https://github.com/AntennaPod/AntennaPod"
    },
    {
      "name": "Apache Superset",
      "icon": "https://avatars.githubusercontent.com/u/47359?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/apache/superset"
    },
    {
      "name": "AppFlowy",
      "icon": "https://avatars.githubusercontent.com/u/86002201?v=4",
      "license": "AGPL-3.0",
      "url": "https://github.com/AppFlowy-IO/AppFlowy"
    },
    {
      "name": "AppImageKit",
      "icon": "https://avatars.githubusercontent.com/u/16617932?v=4",
      "license": "Other",
      "url": "https://github.com/AppImage/AppImageKit"
    },
    {
      "name": "ArchiveBox",
      "icon": "https://avatars.githubusercontent.com/u/74894248?v=4",
      "license": "MIT",
      "url": "https://github.com/ArchiveBox/ArchiveBox"
    },
    {
      "name": "Ardour",
      "icon": "https://avatars.githubusercontent.com/u/1402482?v=4",
      "license": "Other",
      "url": "https://github.com/Ardour/ardour"
    },
    {
      "name": "Arduino IDE",
      "icon": "https://avatars.githubusercontent.com/u/379109?v=4",
      "license": "Other",
      "url": "https://github.com/arduino/Arduino"
    },
    {
      "name": "Argo CD",
      "icon": "https://avatars.githubusercontent.com/u/30269780?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/argoproj/argo-cd"
    },
    {
      "name": "aria2",
      "icon": "https://avatars.githubusercontent.com/u/13545224?v=4",
      "license": "GPL-2.0",
      "url": "https://github.com/aria2/aria2"
    },
    {
      "name": "Aseprite",
      "icon": "https://avatars.githubusercontent.com/u/3853896?v=4",
      "license": null,
      "url": "https://github.com/aseprite/aseprite"
    },
    {
      "name": "Atom",
      "icon": "https://avatars.githubusercontent.com/u/1089146?v=4",
      "license": "MIT",
      "url": "https://github.com/atom/atom"
    },
    {
      "name": "Audacity",
      "icon": "https://avatars.githubusercontent.com/u/11648186?v=4",
      "license": "Other",
      "url": "https://github.com/audacity/audacity"
    },
    {
      "name": "AutoHotkey",
      "icon": "https://avatars.githubusercontent.com/u/1413373?v=4",
      "license": "GPL-2.0",
      "url": "https://github.com/AutoHotkey/AutoHotkey"
    },
    {
      "name": "balenaEtcher",
      "icon": "https://avatars.githubusercontent.com/u/6157842?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/balena-io/etcher"
    },
    {
      "name": "Bambu Studio",
      "icon": "https://avatars.githubusercontent.com/u/96461528?v=4",
      "license": "AGPL-3.0",
      "url": "https://github.com/bambulab/BambuStudio"
    },
    {
      "name": "bat",
      "icon": "https://avatars.githubusercontent.com/u/4209276?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/sharkdp/bat"
    },
    {
      "name": "Beekeeper Studio",
      "icon": "https://avatars.githubusercontent.com/u/53234021?v=4",
      "license": "Other",
      "url": "https://github.com/beekeeper-studio/beekeeper-studio"
    },
    {
      "name": "Bevy",
      "icon": "https://avatars.githubusercontent.com/u/60047606?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/bevyengine/bevy"
    },
    {
      "name": "Bitcoin Core",
      "icon": "https://avatars.githubusercontent.com/u/528860?v=4",
      "license": "MIT",
      "url": "https://github.com/bitcoin/bitcoin"
    },
    {
      "name": "Bitwarden",
      "icon": "https://avatars.githubusercontent.com/u/15990069?v=4",
      "license": "Other",
      "url": "https://github.com/bitwarden/clients"
    },
    {
      "name": "Blender",
      "icon": "https://avatars.githubusercontent.com/u/52924476?v=4",
      "license": "Other",
      "url": "https://github.com/blender/blender"
    },
    {
      "name": "Bootstrap",
      "icon": "https://avatars.githubusercontent.com/u/2918581?v=4",
      "license": "MIT",
      "url": "https://github.com/twbs/bootstrap"
    },
    {
      "name": "bottom",
      "icon": "https://avatars.githubusercontent.com/u/34804052?v=4",
      "license": "MIT",
      "url": "https://github.com/ClementTsang/bottom"
    },
    {
      "name": "bpytop",
      "icon": "https://avatars.githubusercontent.com/u/59659483?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/aristocratos/bpytop"
    },
    {
      "name": "Brave",
      "icon": "https://avatars.githubusercontent.com/u/12301619?v=4",
      "license": "MPL-2.0",
      "url": "https://github.com/brave/brave-browser"
    },
    {
      "name": "Bruno",
      "icon": "https://avatars.githubusercontent.com/u/114530840?v=4",
      "license": "MIT",
      "url": "https://github.com/usebruno/bruno"
    },
    {
      "name": "Bun",
      "icon": "https://avatars.githubusercontent.com/u/108928776?v=4",
      "license": "Other",
      "url": "https://github.com/oven-sh/bun"
    },
    {
      "name": "Caddy",
      "icon": "https://avatars.githubusercontent.com/u/12955528?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/caddyserver/caddy"
    },
    {
      "name": "calibre",
      "icon": "https://avatars.githubusercontent.com/u/1308621?v=4",
      "license": "GPL-3.0",
      "url": "https://github.com/kovidgoyal/calibre"
    },
    {
      "name": "Chakra UI",
      "icon": "https://avatars.githubusercontent.com/u/54212428?v=4",
      "license": "MIT",
      "url": "https://github.com/chakra-ui/chakra-ui"
    },
    {
      "name": "Chocolatey",
      "icon": "https://avatars.githubusercontent.com/u/811025?v=4",
      "license": "Other",
      "url": "https://github.com/chocolatey/choco"
    },
    {
      "name": "Chroma",
      "icon": "https://avatars.githubusercontent.com/u/105881770?v=4",
      "license": "Apache-2.0",
      "url": "https://github.com/chroma-core/chroma"
    },
    {
      "name": "Clementine",
      "icon": "https://avatars.githubusercontent.com/u/5975299?v=4",
      "license": "GPL-3.0",
      "url": "https://github.com/clementine-player/Clementine"
    },
    {
      "name": "Cocos Engine",
      "icon": "https://avatars.githubusercontent.com/u/6937061?v=4",
      "license": "Other",
      "url": "https://github.com/cocos/cocos-engine"
    },
    {
      "name": "Cocos2d-x",
      "icon": "https://avatars.githubusercontent.com/u/234324?v=4",
      "license": null,
      "url": "https://github.com/cocos2d/cocos2d-x"
    }
  ],
  "featured": [
    {
      "name": "Actual Budget",
      "icon": "https://avatars.githubusercontent.com/u/37879538?v=4",
      "trust": 100,
      "category": "finance",
      "url": "https://github.com/actualbudget/actual"
    },
    {
      "name": "balenaEtcher",
      "icon": "https://avatars.githubusercontent.com/u/6157842?v=4",
      "trust": 100,
      "category": "utilities",
      "url": "https://github.com/balena-io/etcher"
    },
    {
      "name": "Brave",
      "icon": "https://avatars.githubusercontent.com/u/12301619?v=4",
      "trust": 100,
      "category": "utilities",
      "url": "https://github.com/brave/brave-browser"
    },
    {
      "name": "Cryptomator",
      "icon": "https://avatars.githubusercontent.com/u/11850518?v=4",
      "trust": 100,
      "category": "security",
      "url": "https://github.com/cryptomator/cryptomator"
    },
    {
      "name": "draw.io",
      "icon": "https://avatars.githubusercontent.com/u/1769238?v=4",
      "trust": 100,
      "category": "productivity",
      "url": "https://github.com/jgraph/drawio-desktop"
    },
    {
      "name": "FreeCAD",
      "icon": "https://avatars.githubusercontent.com/u/2306237?v=4",
      "trust": 100,
      "category": "science",
      "url": "https://github.com/FreeCAD/FreeCAD"
    },
    {
      "name": "Godot",
      "icon": "https://avatars.githubusercontent.com/u/6318500?v=4",
      "trust": 100,
      "category": "development",
      "url": "https://github.com/godotengine/godot"
    },
    {
      "name": "Immich",
      "icon": "https://avatars.githubusercontent.com/u/109746326?v=4",
      "trust": 100,
      "category": "utilities",
      "url": "https://github.com/immich-app/immich"
    }
  ],
  "categories": [
    {
      "slug": "communication",
      "name": "Communication",
      "count": 15,
      "description": "Messaging, email and team chat with end-to-end encryption options."
    },
    {
      "slug": "development",
      "name": "Developer Tools",
      "count": 131,
      "description": "Editors, terminals, runtimes, frameworks and DevOps utilities."
    },
    {
      "slug": "education",
      "name": "Education",
      "count": 7,
      "description": "Flashcards, offline libraries and learning tools."
    },
    {
      "slug": "finance",
      "name": "Finance",
      "count": 11,
      "description": "Budgeting, accounting, portfolios and personal finance."
    },
    {
      "slug": "gaming",
      "name": "Games",
      "count": 36,
      "description": "Open-source games, engines and classic remakes."
    },
    {
      "slug": "graphics",
      "name": "Graphics & Design",
      "count": 20,
      "description": "Image editing, vector art, 3D modelling and design tools."
    },
    {
      "slug": "media",
      "name": "Media",
      "count": 39,
      "description": "Players, editors, streaming servers and audio tools."
    },
    {
      "slug": "productivity",
      "name": "Productivity",
      "count": 33,
      "description": "Notes, documents, calendars and workflow tools that keep work moving."
    },
    {
      "slug": "science",
      "name": "Science & Engineering",
      "count": 50,
      "description": "CAD, simulation, electronics design, GIS and data science."
    },
    {
      "slug": "security",
      "name": "Security & Privacy",
      "count": 38,
      "description": "Password managers, encryption, VPNs and vulnerability scanning."
    },
    {
      "slug": "utilities",
      "name": "Utilities",
      "count": 64,
      "description": "File managers, sync, screenshots, disk imaging and system helpers."
    }
  ],
  "platforms": [
    {
      "name": "iOS",
      "count": 9
    },
    {
      "name": "Android",
      "count": 40
    },
    {
      "name": "Windows",
      "count": 231
    },
    {
      "name": "macOS",
      "count": 174
    },
    {
      "name": "Linux",
      "count": 208
    }
  ],
  "collections": [
    {
      "name": "Featured",
      "description": "Hand-picked open-source apps that set the standard for their category.",
      "count": 18
    },
    {
      "name": "Editors' choice",
      "description": "The highest-trust projects in the catalog, ranked by maintenance signals.",
      "count": 12
    },
    {
      "name": "Privacy essentials",
      "description": "Encryption, private messaging and tracker-blocking you can audit yourself.",
      "count": 11
    },
    {
      "name": "Self-hosted favourites",
      "description": "Run your own cloud, media server and automation stack on hardware you own.",
      "count": 12
    },
    {
      "name": "Daily drivers",
      "description": "The apps people keep installed: browsers, launchers, notes and screenshots.",
      "count": 12
    },
    {
      "name": "For developers",
      "description": "Editors, terminals, runtimes and debugging tools trusted by engineers.",
      "count": 12
    },
    {
      "name": "Open creative suite",
      "description": "A full free pipeline for photo, vector, 3D, audio and video work.",
      "count": 12
    },
    {
      "name": "Open-source gaming",
      "description": "Engines, remakes and full games you can build, mod and share.",
      "count": 12
    }
  ]
};
